package io.arrogantprogrammer.thanksgivingai.domain;

public enum USRegion {

    ALABAMA("SOUTHERN"),
    ALASKA("WESTPAC"),
    ARIZONA("WESTPAC"),
    ARKANSAS("SOUTHERN"),
    CALIFORNIA("WESTPAC"),
    COLORADO("WESTPAC"),
    CONNECTICUT("ATLANTIC"),
    DELAWARE("ATLANTIC"),
    FLORIDA("SOUTHERN"),
    GEORGIA("SOUTHERN"),
    HAWAII("WESTPAC"),
    IDAHO("WESTPAC"),
    ILLINOIS("CENTRAL"),
    INDIANA("CENTRAL"),
    IOWA("CENTRAL"),
    KANSAS("CENTRAL"),
    KENTUCKY("CENTRAL"),
    LOUISIANA("SOUTHERN"),
    MAINE("ATLANTIC"),
    MARYLAND("ATLANTIC"),
    MASSACHUSETTS("ATLANTIC"),
    MICHIGAN("CENTRAL"),
    MINNESOTA("CENTRAL"),
    MISSISSIPPI("SOUTHERN"),
    MISSOURI("CENTRAL"),
    MONTANA("WESTPAC"),
    NEBRASKA("CENTRAL"),
    NEVADA("WESTPAC"),
    NEW_HAMPSHIRE("ATLANTIC"),
    NEW_JERSEY("ATLANTIC"),
    NEW_MEXICO("WESTPAC"),
    NEW_YORK("ATLANTIC"),
    NORTH_CAROLINA("ATLANTIC"),
    NORTH_DAKOTA("CENTRAL"),
    OHIO("CENTRAL"),
    OKLAHOMA("SOUTHERN"),
    OREGON("WESTPAC"),
    PENNSYLVANIA("ATLANTIC"),
    RHODE_ISLAND("ATLANTIC"),
    SOUTH_CAROLINA("SOUTHERN"),
    SOUTH_DAKOTA("WESTPAC"),
    TENNESSEE("SOUTHERN"),
    TEXAS("SOUTHERN"),
    UTAH("WESTPAC"),
    VERMONT("ATLANTIC"),
    VIRGINIA("ATLANTIC"),
    WASHINGTON("WESTPAC"),
    WEST_VIRGINIA("CENTRAL"),
    WISCONSIN("CENTRAL"),
    WYOMING("WESTPAC"),
    AMERICAN_SAMOA("WESTPAC"),
    DISTRICT_OF_COLUMBIA("ATLANTIC"),
    GUAM("WESTPAC"),
    NORTHERN_MARIANA_ISLANDS("WESTPAC"),
    PUERTO_RICO("SOUTHERN"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("WESTPAC"),
    VIRGIN_ISLANDS("SOUTHERN");

    private final String region;

    private USRegion(final String region) {
        this.region = region;
    }

    public String getRegion() {
        return region;
    }
}